# GoReleaser configuration for Rust project
# Binaries are pre-built by GitHub Actions, GoReleaser handles packaging and release
version: 2

project_name: agsipls

dist: dist

before:
  hooks:
    - echo "Using pre-built binaries from GitHub Actions"

# Skip building - we use pre-compiled Rust binaries
builds:
  - skip: true

# Archives configuration  
archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - examples/**/*
      - schemas/**/*
      - GORELEASER.md

# Checksum of all artifacts
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Snapshot builds (for testing)
snapshot:
  version_template: "{{ incpatch .Version }}-next"

# Changelog configuration
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: 'Performance Improvements'
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 20
    - title: 'Documentation'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 30
    - title: 'Other Changes'
      order: 999

# GitHub release configuration
release:
  github:
  draft: false
  prerelease: auto
  mode: append
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## AGSi Tools Release v{{.Version}}
    
    AGSi is a comprehensive toolkit for working with AGSi Ground Model data format.
    
    ### Installation
    
    #### Quick Install (Linux/macOS)
    ```bash
    curl -sSL https://raw.githubusercontent.com/{{ .Env.GITHUB_REPOSITORY }}/main/install.sh | bash
    ```
    
    #### Manual Install
    Download the appropriate archive for your platform from the assets below, extract it, and place the binary in your PATH.
    
    #### Homebrew (macOS/Linux)
    ```bash
    brew install {{ .Env.GITHUB_REPOSITORY_OWNER }}/tap/agsipls
    ```
    
    ### What's Changed
  footer: |
    ---
    
    **Full Changelog**: https://github.com/{{ .Env.GITHUB_REPOSITORY }}/compare/{{ .PreviousTag }}...{{ .Tag }}

# Homebrew tap
brews:
  - repository:
      owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/{{ .Env.GITHUB_REPOSITORY }}
    description: AGSi Ground Model toolkit - CLI and libraries for working with AGSi data
    license: MIT OR Apache-2.0
    test: |
      system "#{bin}/agsipls --version"
    install: |
      bin.install "agsipls"

# Linux packages (deb, rpm, apk)
nfpms:
  - id: packages
    package_name: agsipls
    vendor: AGSi Contributors
    homepage: https://github.com/{{ .Env.GITHUB_REPOSITORY }}
    maintainer: AGSi Contributors
    description: |-
      AGSi Ground Model toolkit
      CLI and libraries for working with AGSi data format
    license: MIT OR Apache-2.0
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    section: utils
    priority: optional
    contents:
      - src: ./README.md
        dst: /usr/share/doc/agsipls/README.md
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/agsipls/LICENSE
        file_info:
          mode: 0644
      - src: ./GORELEASER.md
        dst: /usr/share/doc/agsipls/GORELEASER.md
        file_info:
          mode: 0644

# Announcements (skip for patch releases)
announce:
  skip: '{{gt .Patch 0}}'
