version: '3.8'

services:
  agsi-cli:
    build: .
    image: agsi:latest
    volumes:
      - ./data:/data
    command: --help

  agsi-mcp:
    build: .
    image: agsi:latest
    volumes:
      - ./data:/data
    command: mcp
    stdin_open: true
    tty: true

  agsi-lsp:
    build: .
    image: agsi:latest
    volumes:
      - ./data:/data
    ports:
      - "9257:9257"
    command: lsp --port 9257
