name: Test GoReleaser Config

on:
  pull_request:
    paths:
      - '.goreleaser.yml'
      - '.github/workflows/release.yml'
      - '.github/workflows/goreleaser-test.yml'
  push:
    branches:
      - main
      - master
    paths:
      - '.goreleaser.yml'
      - '.github/workflows/release.yml'
      - '.github/workflows/goreleaser-test.yml'
  workflow_dispatch:

jobs:
  goreleaser-check:
    name: Check GoReleaser Config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run GoReleaser check
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: check

      - name: Run GoReleaser build (snapshot)
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: build --snapshot --clean --single-target
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
